[build]
  publish = "Project-main/ProjectA/HTML"  # ระบุโฟลเดอร์ Publish Directory
  command = ""
[[redirects]]
  from = "/*"
  to = "/Home.html"
  status = 200 
  force = true

[[redirects]]
  from = "/css/*"
  to = "/css/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/poto/art toy/*"
  to = "/poto/art toy/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/poto/model/*"
  to = "/poto/model/:splat"
  status = 200
  force = true
